#!/bin/zsh

who=$(whoami)
if [[ "$who" == "root" ]]; then
  echo "ERROR: you can't activate the environment as root"
  return
fi

BOLD=$(tput bold)
NORMAL=$(tput sgr0)

VENV_DIR="./.$(basename $(pwd))"
OS=$(uname -o)

if [ ! -d $VENV_DIR ]; then
  echo "${BOLD}Creating virtual env${NORMAL}"
  python3 -m venv $VENV_DIR
fi

echo "${BOLD}Activating virtual env${NORMAL}"
source $VENV_DIR/bin/activate

#
## Installing python dependencies
#

echo "${BOLD}Installing python dependencies${NORMAL}"

python3 -m pip install --upgrade pip
python3 -m pip install -e ".[dev]"
